[features]
seeds = false
skip-lint = false

[programs.localnet]
deed_metadata = "HAcjmTqRVugqXdgyMkNyK5Kt4JsTDwn1dMKTbQSJ4i4K"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/eric/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
